### ISSUE TITLE
Translation of Minepedia into Ukrainian

### ISSUE THREAD

**Issue by StarmanMine142** [JimiIT92/Minepedia#2]
Would it be possible for you to add the Ukrainian translation created by me to your mod?

Download in .zip format on https://www.mediafire.com/file/t5ihc746kaw7518/minepedia.zip/file

**Comment by StarmanMine142** [comment]
?

**Comment by StarmanMine142** [comment]
@JimiIT92

**Comment by StarmanMine142** [comment]
@JimiIT92

**Comment by StarmanMine142** [comment]
@JimiIT92 Maybe you will at least somehow react to it?

**Comment by StarmanMine142** [comment]
Just say whether you will add translation to the mod or not

**Comment by StarmanMine142** [comment]
But nobody came

**Comment by JimiIT92** [comment]
Sorry, missed this notification due tot he fact that I was away from home. Yep, I'll add the translations in the 1.21.4 update :D Happy to see more people contributing to the project :)
Slava ukraini! 🇺🇦

**Comment by StarmanMine142** [comment]
THANK YOU!

Heroyam slava!

**Comment by JimiIT92** [comment]
Version 1.3 for Minecraft 1.21.4 has just been released, with Ukrainian language support :D
Check it out here ♥️ [https://modrinth.com/mod/minepedia/version/1.3](https://modrinth.com/mod/minepedia/version/1.3)
